version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      # for local test
      - ./data:/data/db
      # for production
      # - /home/dave/app/pmhealth-mevn/data:/data/db 
    ports:
      - "3002:27017"
  
  # seed file import
  mongo-seed:
    build: ./mongo-seed
    restart: on-failure
    links:
      - mongo
    depends_on:
      - mongo

  backend:
    container_name: project-backend
    restart: on-failure
    build: ./backend
    working_dir: /usr/src/api
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo

  # for local test
  # omit in production server
  frontend:
    container_name: project-frontend
    image: nginx
    restart: on-failure
    volumes:
        - "./frontend/dist:/home/dave/apps/pmhealth-mevn/frontend/dist"
        - "./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
        - "3001:80"
    depends_on:
      - backend
